### ISSUE TITLE
["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"

### ISSUE THREAD

**Issue by dangreen** [thejameskyle/babel-react-optimize#19]
```
Error: /Users/dangreen/github/leadbean/dashboard/app/modals/quick-signup/quick-signup.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression" while parsing file: /Users/dangreen/github/leadbean/dashboard/app/modals/quick-signup/quick-signup.js
TypeError: /Users/dangreen/github/leadbean/dashboard/app/modals/quick-signup/quick-signup.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression" while parsing file: /Users/dangreen/github/leadbean/dashboard/app/modals/quick-signup/quick-signup.jsTypeError: /Users/dangreen/github/leadbean/dashboard/app/modals/quick-signup/quick-signup.js: Property object of JSXMemberExpression expected node to be of a type ["JSXMemberExpression","JSXIdentifier"] but instead got "MemberExpression"
    at Object.validate (/Users/dangreen/github/leadbean/node_modules/babel-types/lib/definitions/index.js:100:13)
    at Object.validate (/Users/dangreen/github/leadbean/node_modules/babel-types/lib/index.js:260:9)
    at NodePath._replaceWith (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/path/replacement.js:193:7)
    at NodePath.replaceWith (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/path/replacement.js:171:8)
    at Object.ReferencedIdentifier (/Users/dangreen/github/leadbean/node_modules/babel-plugin-transform-es2015-modules-commonjs/lib/index.js:58:14)
    at Object.newFn (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/visitors.js:295:17)
    at NodePath._call (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/path/context.js:63:18)
    at NodePath.call (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/path/context.js:47:17)
    at NodePath.visit (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/path/context.js:93:12)
    at TraversalContext.visitQueue (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitSingle (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/context.js:115:19)
    at TraversalContext.visit (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/context.js:184:19)
    at Function.traverse.node (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/index.js:135:17)
    at NodePath.visit (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/path/context.js:103:22)
    at TraversalContext.visitQueue (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/context.js:152:16)
    at TraversalContext.visitMultiple (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/context.js:110:17)
    at TraversalContext.visit (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/context.js:182:19)
    at Function.traverse.node (/Users/dangreen/github/leadbean/node_modules/babel-traverse/lib/index.js:135:17)
```

quick-signup,js
```
import Modal        from 'lib/ui/modal';
import { listener } from 'lib/base-component';
import { validate } from 'lib/ui/form';
import { check }    from 'lib/helpers';
import { render }   from 'react-dom';
import React from 'react';
import $     from 'jquery';

import { 
	Modal as BSModal
} from 'react-bootstrap';

var {  
	email:    checkEmail,
	password: checkPassword
} = check;

export default class QuickSignupModal extends Modal {

	state = {
		...this.state,
		login: false,
		email:      "",
		identifier: "",
		password:   ""
	};

	@validate
	render(isValid) {

		var { login } = this.state;

		return login ? this.login(isValid) : this.register(isValid);
	}

	register(isValid) {
		return (
			<BSModal show={this.state.showModal} onHide={this.close}>
				<BSModal.Header closeButton>
	            	<h4 className="modal-title">{__`Your dashboard almost done!`}</h4>
		        </BSModal.Header>
		        <BSModal.Body>
	                <form action="/auth/local/register" method="post" className="sky-form nomargin">
	                    <fieldset className="nomargin">

	                        <label className="label">{__`Please, enter your E-mail to continue work with LeadBean`}:</label>
	                        <label className="input">
	                            <i className="ico-append fa fa-envelope"/>
	                            <input 
	                            	type      = "email" 
	                            	name      = "email" 
	                            	required
	                            	regexp    = {checkEmail}
	                            	{...this.valueLinkToState("email")}
	                            />
	                            <span className="tooltip tooltip-top-right">{__`Email Address`}</span>
	                        </label>
	                    </fieldset>
	                	<a onClick={() => this.setState({...this.state, login: true})}>{__`Already with us?`}</a>
	                    <footer className="celarfix">
	                        <button disabled={!isValid} type="submit" className="btn btn-primary noradius block fullwidth nomargin">
	                        	<i className="fa fa-check"/> {__`Ok, continue`.toUpperCase()}
	                        </button>
	                    </footer>
	                </form>
		        </BSModal.Body>
		    </BSModal>
		);
	}

	login(isValid) {
		return (
			<BSModal show={this.state.showModal} onHide={this.close}>
				<BSModal.Header closeButton>
	            	<h4 className="modal-title">{__`Sign in`}</h4>
		        </BSModal.Header>
		        <BSModal.Body>
	                <form action="/auth/local" method="post" className="sky-form nomargin">
	                    <fieldset className="nomargin">

	                        <label className="label">{__`E-mail`}</label>
	                        <label className="input">
	                            <i className="ico-append fa fa-envelope"/>
	                            <input 
	                            	type      = "email" 
	                            	name      = "identifier"
	                            	required
	                            	regexp    = {checkEmail}
	                            	{...this.valueLinkToState("identifier")}
	                            />
	                            <span className="tooltip tooltip-top-right">{__`Email Address`}</span>
	                        </label>

		                	<div>
		                        <label className="label margin-top-20">{__`Password`}</label>
		                        <label className="input">
		                            <i className="ico-append fa fa-lock"/>
		                            <input 
		                            	type      = "password" 
		                            	name      = "password"
		                            	required
	                        			regexp    = {checkPassword}
	                        			{...this.valueLinkToState("password")}
		                            />
		                            <b className="tooltip tooltip-top-right">{__`Type your Password`}</b>
		                        </label>
		                	</div> 
	                    </fieldset>
	                    <footer className="celarfix">
	                        <button disabled={!isValid} type="submit" className="btn btn-primary noradius block fullwidth nomargin">
	                        	<i className="fa fa-check"/> {__`Ok, log in`.toUpperCase()}
	                        </button>
	                    </footer>
	                	<div>
		                    <div className="text-center margin-bottom-10">
		                        {__`Or sign in with social`.toUpperCase()}:
		                    </div>

		                    <div className="socials margin-top10 text-center">
		                        <a href="/auth/facebook" className="social-icon social-facebook" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook">
		                            <i className="icon-facebook"/>
		                            <i className="icon-facebook"/>
		                        </a>
		                        <a href="/auth/twitter" className="social-icon social-twitter" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter">
		                            <i className="icon-twitter"/>
		                            <i className="icon-twitter"/>
		                        </a>
		                        <a href="/auth/google" className="social-icon social-google" data-toggle="tooltip" data-placement="top" title="" data-original-title="Google">
		                            <i className="icon-google-plus"/>
		                            <i className="icon-google-plus"/>
		                        </a>
		                        <a href="/auth/vkontakte" className="social-icon social-vk" data-toggle="tooltip" data-placement="top" title="" data-original-title="Vk">
		                            <i className="icon-vk"/>
		                            <i className="icon-vk"/>
		                        </a>
		                    </div>
                        </div>
	                </form>
		        </BSModal.Body>
		    </BSModal>
		);
	}

	componentDidMount() {

		super.componentDidMount(...arguments);

		$(document).on('click', 'a[href="#quick-signup-modal"]', (e) => {
			e.preventDefault();
			this.open();
		});
	}

	clearData() {
		this.setState({ 
			...this.state,
			login: false,
			email:      "",
			identifier: "",
			password:   ""
		});
	}
}

$(renderModal)
function renderModal() {

	var mountPoint = document.querySelector('QuickSignupModal');

	if (mountPoint != null) {
		render(<QuickSignupModal/>, mountPoint);
	}
}
```

**Comment by mewben** [comment]
I'm having this problem too.. It seems to have conflict with react-bootstrap...

**Comment by mewben** [comment]
I solved this error by separating the `Component.SubComponent` syntax.

For example, 
```jsx
<BSModal.Header closeButton>
    <h4 className="modal-title">{__`Sign in`}</h4>
</BSModal.Header>
```
becomes
```jsx
<Header closeButton>
    <h4 className="modal-title">{__`Sign in`}</h4>
</Header>
```
through import
```js
import Modal as BSModal, { Header } from 'react-bootsrap/lib/Modal'
```

Hope this helps. :)

**Comment by MatthewHerbst** [comment]
I'm seeing the same issue. Also found this while researching.  https://phabricator.babeljs.io/T6662

The above fix does indeed fix the issue for me, but that's not a sustainable way to fix the issue in a massive code base. Hoping this gets fixed soon - had to stop using the package for right now :(

**Comment by blackxored** [comment]
I'm also getting this. However I can't fix because after the initial one, thing comes from one of my deps (at least) :(

**Comment by mewben** [comment]
@blackxored You can do this if you have another `Header` import:
```jsx
import Modal as BSModal, { Header as Header2 } from 'react-bootsrap/lib/Modal'
```

**Comment by blackxored** [comment]
@mewben What I'm trying to say is that I don't control the code that uses that kind of import. I have at least one external dependency using `Animated.View` everywhere, it's not feasible to change them all.

**Comment by mewben** [comment]
@blackxored Ooops.. Sorry 'bout that..

**Comment by arypurnomoz** [comment]
Most people who are using react-native have `Animated.View`, `Animated.Text` or `Animated.Image` in their code. I think they will love it if the `Animated.*` syntax is still supported

**Comment by JMacLulich** [comment]
I'm seeing the same problem as well when running the npm command.

`npm run deploy:prod`.

It's happening for me when using a `bootstrap` modal component `Modal`.

@mewben did you manage to get around it?

Failing a proper fix I will have to import the children explicitly as well.

The puzzling thing is the build doesn't fail when using `npm run deploy:dev` there must be an extra step(s) included when the deployment target of `production` is used?

Thankfully, for the moment, I can explicitly import all the children in the `import` statement, but that's a shit long term fix.

**Comment by kiki-le-singe** [comment]
@mewben thanks it works

**Comment by faceyspacey** [comment]
+1 ...we can't easily change all dependencies that refer to `<Animated.View/Etc>`
