### ISSUE TITLE
Export error for `transform-react-pure-class-to-function`

### ISSUE THREAD

**Issue by jhen0409** [thejameskyle/babel-react-optimize#22]
I found a little problem when handling https://github.com/chentsulin/electron-react-boilerplate/issues/278, the following code will broken:

```js
import React from 'react'
export class A extends React.Component {
  render() {
    return (<div></div>)
  }
}
export class B extends React.Component {
  render() {
    return (<div></div>)
  }
}
```

It work fine for `export default`.

The stacktrace:

```
Error: Comp.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (/project_path/node_modules/babel-traverse/lib/path/modification.js:190:13)
    at NodePath.replaceWithMultiple (/project_path/node_modules/babel-traverse/lib/path/replacement.js:93:8)
    at PluginPass.Class (/project_path/node_modules/babel-plugin-transform-react-pure-class-to-function/lib/index.js:96:14)
    at newFn (/project_path/node_modules/babel-traverse/lib/visitors.js:301:19)
    at NodePath._call (/project_path/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/project_path/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/project_path/node_modules/babel-traverse/lib/path/context.js:106:12)
    at TraversalContext.visitQueue (/project_path/node_modules/babel-traverse/lib/context.js:167:16)
    at TraversalContext.visitSingle (/project_path/node_modules/babel-traverse/lib/context.js:118:19)
    at TraversalContext.visit (/project_path/node_modules/babel-traverse/lib/context.js:211:19)
```

**Comment by cj** [comment]
@thejameskyle I'm getting the same error with this code https://gist.github.com/cj/bd5f51ae48e21c8c203d32b34ea5684c

**Comment by cj** [comment]
If you remove the export on line 4 it works just fine, but it should still work with export.

**Comment by cj** [comment]
@thejameskyle So if I add `componentWillMount() {}` inside of the `HomePage` class it works!  Surely this has to be a bug.

**Comment by cj** [comment]
I guess the proper course of action would be to make that a stateless function, which works also.
